-- =============================================================================
-- SSV 1928 Sulzbach e.V. - Wettkampfauswertung
-- Supabase Datenbankschema & RLS-Sicherheitsrichtlinien (SQL)
-- =============================================================================

-- 1. Tabelle: participants (Teilnehmer)
CREATE TABLE IF NOT EXISTS public.participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname TEXT NOT NULL,
    nachname TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabelle: competitions (Wettkämpfe)
CREATE TABLE IF NOT EXISTS public.competitions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    datum DATE NOT NULL,
    anzahl_ergebnisse INTEGER DEFAULT 3 NOT NULL,
    teamgroesse INTEGER DEFAULT 3 NOT NULL,
    status TEXT DEFAULT 'geplant' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabelle: teams (Mannschaften je Wettkampf)
CREATE TABLE IF NOT EXISTS public.teams (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    competition_id UUID REFERENCES public.competitions(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabelle: starts (Starts von Schützen in Wettkämpfen)
-- Wichtig: Ein Teilnehmer kann mehrere Starts im selben Wettkampf haben.
CREATE TABLE IF NOT EXISTS public.starts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    competition_id UUID REFERENCES public.competitions(id) ON DELETE CASCADE NOT NULL,
    participant_id BIGINT REFERENCES public.participants(id) ON DELETE CASCADE NOT NULL,
    team_id UUID REFERENCES public.teams(id) ON DELETE SET NULL,
    ak BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabelle: results (Einzelergebnisse / Serien je Start)
-- Wichtig: Ergebnisse hängen ausschließlich an start_id (nicht an participant_id).
CREATE TABLE IF NOT EXISTS public.results (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    start_id UUID REFERENCES public.starts(id) ON DELETE CASCADE NOT NULL,
    nummer INTEGER NOT NULL,
    wert NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indizes für schnelle Abfragen
CREATE INDEX IF NOT EXISTS idx_teams_competition ON public.teams(competition_id);
CREATE INDEX IF NOT EXISTS idx_starts_competition ON public.starts(competition_id);
CREATE INDEX IF NOT EXISTS idx_starts_participant ON public.starts(participant_id);
CREATE INDEX IF NOT EXISTS idx_starts_team ON public.starts(team_id);
CREATE INDEX IF NOT EXISTS idx_results_start ON public.results(start_id);

-- =============================================================================
-- Row Level Security (RLS) Policies für anonymen / öffentlichen Zugriff
-- =============================================================================

-- RLS aktivieren
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.starts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;

-- 1. Policies für participants
DROP POLICY IF EXISTS "Public select participants" ON public.participants;
DROP POLICY IF EXISTS "Public insert participants" ON public.participants;
DROP POLICY IF EXISTS "Public update participants" ON public.participants;
DROP POLICY IF EXISTS "Public delete participants" ON public.participants;

CREATE POLICY "Public select participants" ON public.participants FOR SELECT USING (true);
CREATE POLICY "Public insert participants" ON public.participants FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update participants" ON public.participants FOR UPDATE USING (true);
CREATE POLICY "Public delete participants" ON public.participants FOR DELETE USING (true);

-- 2. Policies für competitions
DROP POLICY IF EXISTS "Public select competitions" ON public.competitions;
DROP POLICY IF EXISTS "Public insert competitions" ON public.competitions;
DROP POLICY IF EXISTS "Public update competitions" ON public.competitions;
DROP POLICY IF EXISTS "Public delete competitions" ON public.competitions;

CREATE POLICY "Public select competitions" ON public.competitions FOR SELECT USING (true);
CREATE POLICY "Public insert competitions" ON public.competitions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update competitions" ON public.competitions FOR UPDATE USING (true);
CREATE POLICY "Public delete competitions" ON public.competitions FOR DELETE USING (true);

-- 3. Policies für teams
DROP POLICY IF EXISTS "Public select teams" ON public.teams;
DROP POLICY IF EXISTS "Public insert teams" ON public.teams;
DROP POLICY IF EXISTS "Public update teams" ON public.teams;
DROP POLICY IF EXISTS "Public delete teams" ON public.teams;

CREATE POLICY "Public select teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Public insert teams" ON public.teams FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update teams" ON public.teams FOR UPDATE USING (true);
CREATE POLICY "Public delete teams" ON public.teams FOR DELETE USING (true);

-- 4. Policies für starts
DROP POLICY IF EXISTS "Public select starts" ON public.starts;
DROP POLICY IF EXISTS "Public insert starts" ON public.starts;
DROP POLICY IF EXISTS "Public update starts" ON public.starts;
DROP POLICY IF EXISTS "Public delete starts" ON public.starts;

CREATE POLICY "Public select starts" ON public.starts FOR SELECT USING (true);
CREATE POLICY "Public insert starts" ON public.starts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update starts" ON public.starts FOR UPDATE USING (true);
CREATE POLICY "Public delete starts" ON public.starts FOR DELETE USING (true);

-- 5. Policies für results
DROP POLICY IF EXISTS "Public select results" ON public.results;
DROP POLICY IF EXISTS "Public insert results" ON public.results;
DROP POLICY IF EXISTS "Public update results" ON public.results;
DROP POLICY IF EXISTS "Public delete results" ON public.results;

CREATE POLICY "Public select results" ON public.results FOR SELECT USING (true);
CREATE POLICY "Public insert results" ON public.results FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update results" ON public.results FOR UPDATE USING (true);
CREATE POLICY "Public delete results" ON public.results FOR DELETE USING (true);
